# This is a basic workflow that uses Capistrano to deploy Expertiza on Production, Test, and Development servers
name: Deploy with Capistrano

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'test'
        type: choice
        options:
          - production
          - development
          - test

jobs:
  production:
    if: inputs.environment == 'production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true
          
      - name: Create Encrypted SSH Key File
        run: echo "${{ secrets.ENC_RSA_KEY_CONTENT }}" > config/deploy_id_rsa_enc

      - name: Verify File Exists and Check Contents
        run: |
          echo "Checking if file exists and has content..."
          ls -l config/deploy_id_rsa_enc

      - name: Decrypt SSH Key
        run: |
          /usr/bin/openssl enc -d -aes-256-cbc -md sha512 -salt -in config/deploy_id_rsa_enc -out config/deploy_id_rsa -k "${{ secrets.ENC_RSA_KEY_VAL }}" -a -pbkdf2
          chmod 600 config/deploy_id_rsa

      - uses: miloserdow/capistrano-deploy@master
        with:
          target: production # Defines the environment for the deployment
          # enc_rsa_key_val: ${{ secrets.ENCRYPTED_PRIVATE_KEY_PROD }}
          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}

# development and test jobs are identical - with different target environment and server keys
  development:
    if: inputs.environment == 'development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true
      - uses: miloserdow/capistrano-deploy@master
        with:
          target: development
          enc_rsa_key_val: ${{ secrets.ENCRYPTED_PRIVATE_KEY_DEV }}
          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}

  test:
    if: inputs.environment == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true
      - uses: miloserdow/capistrano-deploy@master
        with:
          target: staging
          enc_rsa_key_val: ${{ secrets.ENCRYPTED_PRIVATE_KEY_STAGING }}
          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
